
document.getElementById("calculate").addEventListener("click", () => {
    const rooms = Number(document.getElementById("rooms").value);
    const electricity = Number(document.getElementById("electricity").value);
    const gas = Number(document.getElementById("gas").value);

    const elec_kg = electricity * 0.42;
    const gas_kg = gas * 5.3;
    const total = elec_kg + gas_kg;

    document.getElementById("resultsText").innerHTML = `
        <strong>Total CO₂:</strong> ${total.toLocaleString()} kg/year<br>
        <strong>Electricity:</strong> ${elec_kg.toLocaleString()} kg<br>
        <strong>Gas:</strong> ${gas_kg.toLocaleString()} kg
    `;
});

document.getElementById("exportPDF").addEventListener("click", generatePDF);

async function generatePDF() {
    const { jsPDF } = window.jspdf;

    const pdf = new jsPDF("p", "pt", "a4");
    const resultsNode = document.getElementById("resultsSection");

    const canvas = await html2canvas(resultsNode, { scale: 2 });
    const imgData = canvas.toDataURL("image/png");

    pdf.setFont("Helvetica","bold");
    pdf.setFontSize(20);
    pdf.text("Hotel Sustainability Report", 40, 50);

    pdf.setFontSize(12);
    pdf.setFont("Helvetica","normal");
    pdf.text("Generated by LCA Tool", 40, 70);

    pdf.addImage(imgData, "PNG", 40, 100, 520, 0);

    pdf.save("Hotel_Sustainability_Report.pdf");
}
